# Project Name
TARGET = patch.init_patch

# Sources
CPP_SOURCES = patch.init_patch.cpp

# Library Locations
LIBDAISY_DIR = ../../../daisy-examples/libDaisy/
DAISYSP_DIR = ../../../daisy-examples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
